// expr_parity.test.mjs — adversarial JS <-> Python parity of the expression
// engine (SPEC_EXPR E1/E2): docs/js/expr.js + derive.js (the web app) against
// the Python report script generated by docs/js/pyexport.js.
//
// Part 1 (synthetic): a NetCDF-3 file written with scipy (dims a(3), b(4);
// scalars and 1-D/2-D variables in both dim orders; NaN, +-0, +-Inf, huge,
// tiny and subnormal values; units dBm/mW/W/V/Hz/ns...; a variable named like
// a function; names that need quoting). >= 2000 seeded random expressions
// (every operator, unary +/-, ^ / ** chains, every function, SI suffixes,
// quoted names, random whitespace), mutated (mostly invalid) texts, hand-made
// edge cases and deep nesting are evaluated
//   - JS: parseExpr/evalExpr (raw values, broadcast by dim name), exprUnits,
//     and registerDerived on a formula def;
//   - Python: the script's own helpers (parse_expr, eval_on, expr_units,
//     compute_derived) loaded with runpy, as tests/py/probe_helpers.py does,
//     AND the script run end to end with --dump-derived.
// Required: same accept/reject, same names, dims and units, values bit for bit
// for + - * / (and unary), rel 1e-12 otherwise, NaN <-> NaN. Random reduce
// defs with expression windows are compared the same way (rel 1e-9).
// Part 2 (real files: darpa, sidebands, powercal_hdf5): expression windows
// (range, center, outside_within, RBW-proportional widths, k*f harmonics, SI
// offsets, derived centers), formulas and expected errors through the script's
// --dump-derived vs registerDerived (rel 1e-9, NaN <-> NaN, dims, units).
// Every mismatch is shrunk to a minimal repro and printed.
//
// Run:  NCX_PYTHON=/path/to/python node tests/expr_parity.test.mjs
// Without NCX_PYTHON it is skipped. NCX_SEED / NCX_N change the seed and the
// number of random expressions; NCX_KEEP=1 keeps the temp folder.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import readline from "node:readline";
import { spawn, spawnSync } from "node:child_process";
import { DATA_DIR, PYTHON, loadDataset, dataFile, haveData, moduleUrl, check, skip, summary } from "./node_env.mjs";

if (!process.env.NCX_PYTHON) {
  skip("expr parity", "NCX_PYTHON is not set");
  summary("expr_parity");
  process.exit(0);
}
{
  const r = spawnSync(PYTHON, ["-c", "import numpy, scipy, xarray, matplotlib; print('ok')"], { encoding: "utf8" });
  if (r.status !== 0 || !String(r.stdout).includes("ok")) {
    skip("expr parity", `${PYTHON} lacks numpy/scipy/xarray/matplotlib`);
    summary("expr_parity");
    process.exit(0);
  }
}

const E = await import(moduleUrl("expr.js"));
const D = await import(moduleUrl("derive.js"));
const P = await import(moduleUrl("pyexport.js"));
const X = await import(moduleUrl("explore.js"));
const PJ = await import(moduleUrl("project.js"));

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "ncx-exprpar-"));
const KEEP = !!process.env.NCX_KEEP;
const SEED = Number(process.env.NCX_SEED || 20261002) >>> 0;
const N_RANDOM = Math.max(2000, Number(process.env.NCX_N || 2400) | 0);
const hasOwn = (o, k) => o != null && Object.prototype.hasOwnProperty.call(o, k);
const prod = (a) => a.reduce((p, q) => p * q, 1);

// ============================================================ Python side
const MK_PY = String.raw`
import sys
import numpy as np
from scipy.io import netcdf_file

nan, inf = float("nan"), float("inf")


def write(path, dims, variables):
    f = netcdf_file(path, "w", version=2)
    for d, n in dims:
        f.createDimension(d, n)
    for name, vdims, data, units, dtype, attrs in variables:
        v = f.createVariable(name, dtype, vdims)
        if dtype == "c":
            v[...] = np.array([[c.encode() for c in row] for row in data], dtype="S1")
        else:
            v[...] = np.asarray(data, dtype=dtype)
        if units is not None:
            v.units = units
        for k, val in attrs.items():
            setattr(v, k, val)
    f.close()


def V(name, vdims, data, units=None, dtype="d", **attrs):
    return (name, vdims, data, units, dtype, attrs)


# main synthetic file: every variable here may appear in random expressions
write(sys.argv[1], [("a", 3), ("b", 4)], [
    V("s0", (), 2.5, "V"), V("sneg", (), -3.0, "V"), V("snan", (), nan, ""),
    V("szero", (), 0.0, "mW"), V("snz", (), -0.0, "W"),
    V("va", ("a",), [1.5, -2.0, 0.0], "dBm"),
    V("vb", ("b",), [1e300, -1e-300, 4.0, nan], "mW"),
    V("b", ("b",), [10.0, 20.0, 30.0, 40.0], "Hz"),
    V("m", ("a", "b"), [[1.0, -0.0, nan, 5e-324], [1e308, -1e308, 2.0, -3.0], [0.0, 7.0, 1e-300, inf]], "dBm"),
    V("n", ("b", "a"), [[0.5, -0.25, 3.0], [1e-10, 1e10, -7.0], [100.0, 0.0, nan], [-1.0, 2.0, 1e-5]], "W"),
    V("t", ("a",), [1.0, 2.0, 3.0], "ns"),
    V("vinf", ("a",), [inf, -inf, 1.0], "dB"),
    V("odd name", ("a",), [0.5, 2.0, -1.0], "dB"),
    V("wl.nm", ("b",), [1550.1, 1550.2, 1550.3, 1550.4], "nm"),
    V("1st", (), 7.0, "W"),
    V("max", ("a",), [3.0, 1.0, 2.0], "dBm"),
    V("ib", ("b",), [1, -2, 3, 0], "", "i"),
    V("big", ("a", "b"), [[1e200, -1e150, 3e300, 1e-200], [-2e250, 5e100, 1e154, -1e155], [7e307, 1.5, -0.5, 1e-310]], ""),
    V("tiny", ("b",), [1e-310, -5e-324, 2.2250738585072014e-308, 0.0], "V"),
])
# edge file: names / units / storage details outside the expression language
write(sys.argv[2], [("a", 3), ("b", 4), ("nchar", 5)], [
    V("pi", (), 3.0, "rad"),
    V("tm", ("b",), [1.0, 2.0, 3.0, 4.0], " minutes"),
    V("label", ("a", "nchar"), ["abcde", "fghij", "klmno"], None, "c"),
    V("x", ("a",), [-10.0, -20.0, -30.0], "dBm"),
    V("bom", ("a",), [-11.0, -21.0, -31.0], "﻿dBm".encode("utf-8")),
    V("us1", ("a",), [-12.0, -22.0, -32.0], "dBm\x1f"),
    V("sc", ("a",), [1, 2, 3], "V", "h", scale_factor=0.5, add_offset=10.0),
    V("t", ("a",), [1.0, 2.0, 3.0], "ns"),
    # a UTF-8 name as netCDF-C writes it (scipy writes names as latin1, so pass
    # the UTF-8 bytes): it needs quoting in an expression
    V("pwr µW".encode("utf-8").decode("latin1"), ("a",), [1.0, 2.0, 4.0], "uW"),
    # a value close to (not equal to) a huge _FillValue
    V("fv", ("a",), [1.0, 1.0000001e36, 2.0], "V", _FillValue=1e36),
])
print("ok")
`;

// JSON-lines server: loads the generated script as a module (main() does not
// run) and evaluates expressions / derived defs with its own helpers
const PROBE_PY = String.raw`
import json
import math
import runpy
import sys
import traceback

import numpy as np

_out = sys.stdout
sys.stdout = sys.stderr            # nothing but replies on the real stdout
ns = runpy.run_path(sys.argv[1], run_name="ncx_parity_probe")
ExprError = ns["ExprError"]
files = {}


def enc(x):
    x = float(x)
    if math.isnan(x):
        return "NaN"
    if math.isinf(x):
        return "Infinity" if x > 0 else "-Infinity"
    return x


def arr(a):
    return [enc(v) for v in np.ravel(np.asarray(a, dtype=float)).tolist()]


def err(e):
    if isinstance(e, ExprError):
        return {"error": str(e), "pos": e.pos}
    return {"error": "%s: %s" % (type(e).__name__, str(e)[:300]), "pos": None, "crash": type(e).__name__}


def clear(f):
    for k in [k for k, v in f._vars.items() if v.derived]:
        del f._vars[k]


def one_expr(f, text):
    r = {}
    try:
        node = ns["parse_expr"](text)
    except Exception as e:
        node = None
        r["parse"] = err(e)
    if node is not None:
        try:
            r["names"] = ns["expr_names"](node)
            r["units"] = ns["expr_units"](node, lambda n: ns["name_units"](f, n))
        except Exception as e:
            r["units_crash"] = err(e)
        try:
            dims = []
            for nm in ns["expr_name_nodes"](node):
                for d in ns["name_dims"](f, nm.value, nm.pos):
                    if d not in dims:
                        dims.append(d)
            shape = tuple(f.size(d) for d in dims)
            vals = np.broadcast_to(ns["eval_on"](f, node, dims), shape)
            r["raw"] = {"dims": dims, "data": arr(vals)}
        except Exception as e:
            r["raw"] = err(e)
    name = "zz_parity"
    clear(f)
    st = ns["compute_derived"]({f.name: f}, [{"name": name, "file": f.name, "kind": "formula", "units": "",
                                              "description": "", "expr": text}], lambda m: None)
    e = st.get((f.name, name))
    if e:
        r["formula"] = {"error": e}
    else:
        v = f.var(name)
        r["formula"] = {"dims": list(v.dims), "units": v.units, "data": arr(v.data)}
    clear(f)
    return r


def dec(v):
    return float(v) if isinstance(v, str) else v


def apply(ops):
    """One operation per entry, on given inputs (each a scalar or an array of
    the shape it has in the real evaluation), through the script's evaluator."""
    Node = ns["Node"]
    res = []
    for o in ops:
        vals = []
        for a in o["args"]:
            if "s" in a:
                vals.append(np.float64(dec(a["s"])))
            else:
                vals.append(np.array([dec(v) for v in a["v"]], dtype=float).reshape(a["shape"]))
        node = Node(o["kind"], o["value"], [Node("name", "x%d" % i, (), -1) for i in range(len(vals))], -1)
        try:
            r = ns["eval_expr"](node, lambda name, pos: vals[int(name[1:])])
            res.append(arr(np.broadcast_to(r, tuple(o["shape"]))))
        except Exception as e:
            res.append({"error": "%s: %s" % (type(e).__name__, e)})
    return res


def derive(f, defs):
    clear(f)
    st = ns["compute_derived"]({f.name: f}, defs, lambda m: None)
    out = {}
    for d in defs:
        e = st.get((f.name, d["name"]), "no status")
        if e:
            out[d["name"]] = {"error": e}
        else:
            v = f.var(d["name"])
            out[d["name"]] = {"dims": list(v.dims), "units": v.units, "data": arr(v.data)}
    clear(f)
    return out


for line in sys.stdin:
    if not line.strip():
        continue
    try:
        req = json.loads(line)
        op = req["op"]
        if op == "open":
            files[req["key"]] = ns["DataFile"](req["key"], req["path"])
            res = {"ok": True}
        elif op == "exprs":
            f = files[req["key"]]
            res = {"results": [one_expr(f, t) for t in req["exprs"]]}
        elif op == "derive":
            res = {"results": derive(files[req["key"]], req["defs"])}
        elif op == "apply":
            res = {"results": apply(req["ops"])}
        else:
            res = {"fatal": "unknown op"}
    except Exception:
        res = {"fatal": traceback.format_exc()}
    _out.write("@@" + json.dumps(res, allow_nan=False) + "\n")
    _out.flush()
`;

function runPy(args, opts = {}) {
  const r = spawnSync(PYTHON, args, { encoding: "utf8", timeout: 600000, maxBuffer: 256 << 20, ...opts });
  return { status: r.status, out: (r.stdout || "") + (r.stderr || ""), error: r.error };
}
// JSON with every non-ASCII UTF-16 unit escaped (lone surrogates survive)
const asciiJSON = (o) => JSON.stringify(o).replace(/[\u007f-￿]/g,
  (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"));
const dec = (v) => (typeof v === "string" ? Number(v) : v);

class PyProbe {
  constructor(script) {
    this.proc = spawn(PYTHON, [path.join(TMP, "probe.py"), script], { stdio: ["pipe", "pipe", "pipe"],
      env: { ...process.env, PYTHONIOENCODING: "utf-8" } });
    this.queue = [];
    this.stderr = "";
    this.proc.stderr.on("data", (b) => { this.stderr = (this.stderr + b).slice(-4000); });
    this.done = new Promise((res) => this.proc.on("exit", res));
    this.proc.on("exit", (code) => { for (const q of this.queue.splice(0)) q.reject(new Error(`probe exited (${code}): ${this.stderr}`)); });
    readline.createInterface({ input: this.proc.stdout }).on("line", (line) => {
      if (!line.startsWith("@@")) return;
      const q = this.queue.shift();
      if (!q) return;
      const res = JSON.parse(line.slice(2));
      if (res.fatal) q.reject(new Error("probe: " + res.fatal)); else q.resolve(res);
    });
  }
  req(obj) {
    return new Promise((resolve, reject) => {
      this.queue.push({ resolve, reject });
      this.proc.stdin.write(asciiJSON(obj) + "\n");
    });
  }
  close() { this.proc.stdin.end(); return this.done; }   // resolves when python has exited
}

// ============================================================ project / script builders
const WIN = (o = {}) => ({ mode: "none", lo: "", hi: "", lo2: "", hi2: "", center: "", halfwidth: "", halfwidth2: "", ...o });
const RD = (name, file, src, over, xsrc, win, region, stat, db = "auto") => ({ name, file, kind: "reduce", units: "",
  description: "", src, over, xsrc, window: WIN(win), region, stat, db });
const FM = (name, file, expr, units = "") => ({ name, file, kind: "formula", units, description: "", expr });

// one tab per file: a visible trace of a real variable (so a page is drawn)
// plus an invisible trace per derived def (so neededDerived exports them all)
function reportProject(tabsSpec, defs) {
  const tabs = tabsSpec.map(({ file, v, lineDim, xsrc, slices }) => {
    const traces = [X.makeTrace(file, v, lineDim, xsrc, "", slices || {})];
    for (const d of defs) {
      if (d.file !== file) continue;
      traces.push({ ...X.makeTrace(file, d.name, "", "index", "", {}), visible: false });
    }
    return { name: file, plotcfg: { ...X.DEFAULT_PLOTCFG }, traces, markers: [], cur: 0 };
  });
  return JSON.parse(JSON.stringify(PJ.buildProject({ tabs, active: 0, fileOrder: tabsSpec.map((t) => t.file),
    wantedFiles: [], derived: defs })));
}

// ============================================================ JS side
const isNumVar = (v) => !!v && v.isNumeric() && v.data != null && typeof v.data !== "string"
  && typeof v.data.length === "number";
const jsUnitsOf = (ds) => (n) => { const v = hasOwn(ds.vars, n) ? ds.vars[n] : null; return isNumVar(v) ? X.unitsOf(v) : ""; };

// values with dims vd / shape vs broadcast onto (dims, shape) by dim NAME
function bcast(vals, vd, vs, dims, shape) {
  const st = [];
  let acc = 1;
  for (let i = vs.length - 1; i >= 0; i--) { st[i] = acc; acc *= vs[i]; }
  const total = prod(shape), out = new Float64Array(total), idx = new Array(dims.length).fill(0);
  for (let f = 0; f < total; f++) {
    let o = 0;
    dims.forEach((d, j) => { const i = vd.indexOf(d); if (i >= 0) o += idx[j] * st[i]; });
    out[f] = vals[o];
    for (let j = dims.length - 1; j >= 0; j--) { if (++idx[j] < shape[j]) break; idx[j] = 0; }
  }
  return out;
}

// the names of an expression resolved the way derive.js does (numeric var |
// dim | pi), result dims in first-appearance order, and an evalExpr lookup
function jsBind(ds, ast) {
  const refs = E.exprRefs(ast);
  const dims = [], shape = [], binds = new Map();
  for (const { name, pos } of refs) {
    const v = hasOwn(ds.vars, name) ? ds.vars[name] : null;
    let b;
    if (isNumVar(v)) b = { kind: "var", v, dims: v.dims, shape: v.shape };
    else if (hasOwn(ds.dims, name)) b = { kind: "dim", dims: [name], shape: [ds.dims[name]] };
    else if (name === "pi") b = { kind: "const", dims: [], shape: [] };
    else throw new E.ExprError(v ? `'${name}' is not numeric` : `unknown name '${name}'`, pos);
    binds.set(name, b);
    b.dims.forEach((d, i) => { if (!dims.includes(d)) { dims.push(d); shape.push(b.shape[i]); } });
  }
  const total = prod(shape);
  const lookup = (name) => {
    const b = binds.get(name);
    if (!b || b.kind === "const") return undefined;
    if (b.kind === "dim") return bcast(Float64Array.from({ length: b.shape[0] }, (_, i) => i), b.dims, b.shape, dims, shape);
    const vals = X.asFloatArray(b.v.data, b.v.attrs && b.v.attrs.units);
    return b.dims.length ? bcast(vals, b.dims, b.shape, dims, shape) : vals[0];
  };
  return { dims, shape, total, lookup, binds };
}
// the expression the way derive.js reads it, but with RAW results (+-Inf kept)
function jsRaw(ds, ast) {
  const b = jsBind(ds, ast);
  return { dims: b.dims, data: E.evalExpr(ast, b.lookup, b.total) };
}

// Node-by-node re-check of a value mismatch outside + - * /: every operation
// of the expression is applied by the script to JS's own inputs for it (same
// shapes as in the real evaluation: numpy takes other paths for scalars). Exact
// operations must agree bit for bit (sign of zero included), rounded library
// functions (exp, logs, pow ...) to 4 ulp. If every operation agrees, the
// difference is 1-ulp library rounding amplified by an ill-conditioned
// expression (e.g. log(exp(7n))), not an engine mismatch.
const ROUNDED = new Set(["exp", "ln", "log", "log10", "db2lin", "lin2db", "pow", "^"]);
const encNum = (v) => (Object.is(v, -0) ? "-0" : Number.isFinite(v) ? v : String(v));
const fmtNum = (v) => (Object.is(v, -0) ? "-0" : String(v));
function localPlan(ds, text) {
  const ast = E.parseExpr(text);
  const b = jsBind(ds, ast);
  const st = [];
  for (let i = b.shape.length - 1, acc = 1; i >= 0; i--) { st[i] = acc; acc *= b.shape[i]; }
  // a subtree's values in the shape numpy gives it (1 along dims it lacks)
  const asArg = (nd, full) => {
    const keep = new Set(E.exprNames(nd).flatMap((n) => b.binds.get(n).dims));
    if (!keep.size) return { s: encNum(full[0]) };
    const sub = b.dims.map((d, j) => (keep.has(d) ? b.shape[j] : 1));
    const v = [], idx = sub.map(() => 0);
    for (let f = 0, n = prod(sub); f < n; f++) {
      let o = 0;
      for (let j = 0; j < sub.length; j++) o += idx[j] * st[j];
      v.push(encNum(full[o]));
      for (let j = sub.length - 1; j >= 0; j--) { if (++idx[j] < sub[j]) break; idx[j] = 0; }
    }
    return { v, shape: sub };
  };
  const ops = [];
  const walk = (nd) => {
    let kids, kind, value = null;
    if (nd.type === "bin") { kids = [nd.left, nd.right]; kind = "op"; value = nd.op; }
    else if (nd.type === "unary") { kids = [nd.arg]; kind = nd.op === "-" ? "neg" : "plus"; }
    else if (nd.type === "call") { kids = nd.args; kind = "call"; value = nd.fn; }
    else return;
    kids.forEach(walk);
    const args = kids.map((c) => asArg(c, E.evalExpr(c, b.lookup, b.total)));
    ops.push({ js: E.evalExpr(nd, b.lookup, b.total), fn: value || kind, text: printAst(nd).t,
      req: { kind, value, args, shape: b.shape } });
  };
  walk(ast);
  return ops;
}
function localDiff(o, a) {
  if (!Array.isArray(a)) return `${o.text}: python failed (${a && a.error})`;
  for (let i = 0; i < o.js.length; i++) {
    const x = o.js[i], y = dec(a[i]);
    if ((x !== x && y !== y) || Object.is(x, y)) continue;
    if (ROUNDED.has(o.fn) && Number.isFinite(x) && Number.isFinite(y) && x !== 0 && y !== 0 && ulpDist(x, y) <= 4) continue;
    return `operation ${JSON.stringify(o.text)} [${i}]: js ${fmtNum(x)} vs py ${fmtNum(y)} on the same inputs`;
  }
  return "";
}

function jsOne(ds, text) {
  const r = {};
  let ast = null;
  try { ast = E.parseExpr(text); } catch (e) {
    if (!(e instanceof E.ExprError)) r.parse = { error: "CRASH " + e.message, pos: null, crash: true };
    else r.parse = { error: e.message, pos: e.pos };
  }
  if (ast) {
    r.names = E.exprNames(ast);
    r.units = E.exprUnits(ast, jsUnitsOf(ds));
    try { r.raw = jsRaw(ds, ast); } catch (e) {
      r.raw = e instanceof E.ExprError ? { error: e.message, pos: e.pos } : { error: "CRASH " + e.message, pos: null, crash: true };
    }
  }
  const st = D.registerDerived(ds, [FM("zz_parity", ds.filename, text)]).get("zz_parity");
  if (st && st.ok) {
    const v = ds.vars.zz_parity;
    r.formula = { dims: v.dims.slice(), units: String(v.attrs.units), data: Float64Array.from(v.data) };
  } else r.formula = { error: st ? st.error : "no status" };
  D.unregisterDerived(ds);
  r.exact = !!ast && isExactAst(ast);
  return r;
}
// only + - * / and unary +/- (IEEE, must be bit-identical)
function isExactAst(nd) {
  if (nd.type === "call") return false;
  if (nd.type === "bin") return nd.op !== "^" && isExactAst(nd.left) && isExactAst(nd.right);
  if (nd.type === "unary") return isExactAst(nd.arg);
  return true;
}

// ============================================================ comparison
function ulpDist(a, b) {
  const buf = new DataView(new ArrayBuffer(16));
  buf.setFloat64(0, a); buf.setFloat64(8, b);
  const ia = buf.getBigInt64(0), ib = buf.getBigInt64(8);
  const ord = (i) => (i < 0n ? -(i & 0x7fffffffffffffffn) : i);
  const d = ord(ia) - ord(ib);
  return Number(d < 0n ? -d : d);
}
function sameNum(a, b, exact, rel) {
  if (a !== a || b !== b) return a !== a && b !== b;
  if (exact) return Object.is(a, b);
  if (a === b) return true;
  if (!Number.isFinite(a) || !Number.isFinite(b)) return false;
  return Math.abs(a - b) <= rel * Math.max(Math.abs(a), Math.abs(b)) || ulpDist(a, b) <= 2;
}
function firstDiff(a, b, exact, rel) {
  if (!a || !b) return "missing values";
  if (a.length !== b.length) return `length ${a.length} vs ${b.length}`;
  for (let i = 0; i < a.length; i++) {
    const x = a[i], y = dec(b[i]);
    if (!sameNum(x, y, exact, rel)) return `[${i}] js ${Object.is(x, -0) ? "-0" : x} vs py ${Object.is(y, -0) ? "-0" : y}`;
  }
  return "";
}
const crashed = (o) => !!(o && o.crash);
const fmtErr = (o) => (o ? `${o.error}${o.pos !== undefined && o.pos !== null ? ` @${o.pos}` : ""}` : "ok");

// -> [{cat, detail}] (empty: agree)
function compareExpr(js, py) {
  const out = [];
  const add = (cat, detail) => out.push({ cat, detail });
  if (crashed(py.parse) && !js.parse) add("py-crash-parse", `py ${fmtErr(py.parse)}`);
  else if (!!js.parse !== !!py.parse) add("parse-accept", `js ${fmtErr(js.parse)} | py ${fmtErr(py.parse)}`);
  else if (js.parse && js.parse.pos !== py.parse.pos && !crashed(py.parse))
    add("parse-pos", `js ${fmtErr(js.parse)} | py ${fmtErr(py.parse)}`);
  if (!js.parse && !py.parse) {
    if (py.units_crash) add("py-crash-units", fmtErr(py.units_crash));
    else {
      if (JSON.stringify(js.names) !== JSON.stringify(py.names)) add("names", `js ${JSON.stringify(js.names)} | py ${JSON.stringify(py.names)}`);
      if (js.units !== py.units) add("units", `js ${JSON.stringify(js.units)} | py ${JSON.stringify(py.units)}`);
    }
    const jr = js.raw, pr = py.raw;
    if (crashed(pr) && !jr.error) add("py-crash-eval", fmtErr(pr));
    else if (!!jr.error !== !!pr.error) add("eval-accept", `js ${fmtErr(jr.error ? jr : null)} | py ${fmtErr(pr.error ? pr : null)}`);
    else if (jr.error && jr.pos !== pr.pos && !crashed(pr)) add("eval-pos", `js ${fmtErr(jr)} | py ${fmtErr(pr)}`);
    else if (!jr.error) {
      if (JSON.stringify(jr.dims) !== JSON.stringify(pr.dims)) add("raw-dims", `js ${JSON.stringify(jr.dims)} | py ${JSON.stringify(pr.dims)}`);
      else {
        const d = firstDiff(jr.data, pr.data, js.exact, 1e-12);
        if (d) add(js.exact ? "raw-value-exact" : "raw-value", d);
      }
    }
  }
  const jf = js.formula, pf = py.formula;
  if (!!jf.error !== !!pf.error) add("formula-accept", `js ${jf.error || "ok"} | py ${pf.error || "ok"}`);
  else if (!jf.error) {
    if (JSON.stringify(jf.dims) !== JSON.stringify(pf.dims)) add("formula-dims", `js ${JSON.stringify(jf.dims)} | py ${JSON.stringify(pf.dims)}`);
    if (jf.units !== pf.units) add("formula-units", `js ${JSON.stringify(jf.units)} | py ${JSON.stringify(pf.units)}`);
    const d = JSON.stringify(jf.dims) === JSON.stringify(pf.dims) ? firstDiff(jf.data, pf.data, js.exact, 1e-12) : "";
    if (d) add(js.exact ? "formula-value-exact" : "formula-value", d);
  }
  return out;
}

// ============================================================ random expressions
function mulberry32(a) {
  return () => {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(SEED);
const ri = (n) => Math.floor(rnd() * n);
const pick = (a) => a[ri(a.length)];
const chance = (p) => rnd() < p;

const MU1 = "µ", MU2 = "μ";
const NAME_POOL = ["s0", "sneg", "snan", "szero", "snz", "va", "vb", "b", "a", "m", "n", "t", "vinf",
  '"odd name"', '"wl.nm"', '"1st"', "max", '"max"', "ib", "big", "tiny", "pi", '"pi"', '"m"', '"a"', '"va"'];
const NUM_POOL = ["0", "1", "2", "3", "0.5", ".5", "1.", "10", "1e3", "2.5E-3", "1e-7", "1e308", "1e309",
  "1e-320", "5e-324", "123456789.123456789", "0.1", "0.2", "0.3", "1.7976931348623157e308", "4.9e-324",
  "5k", "2.5M", "10u", "3" + MU1, "4" + MU2, "1p", "7n", "2m", "3K", "1G", "2T", "2e3k", "1.5e-3M", ".5k",
  "1.k", "9e307k", "1e-310p", "0.1m", "100", "1000000", "0.000001", "7"];
const EXP_POOL = ["2", "0.5", "3", "1e21", "1e-7", "1u", "2.5M", "1e309", ".5", "123456789012345678901234",
  "0.000001", "1.5e-6", "1e+21", "100", "0", "1"];
const FN = [["abs", 1], ["sqrt", 1], ["exp", 1], ["ln", 1], ["log", 1], ["log10", 1], ["floor", 1], ["ceil", 1],
  ["round", 1], ["db2lin", 1], ["lin2db", 1], ["pow", 2], ["min", -1], ["max", -1]];
const P_ADD = 1, P_MUL = 2, P_UN = 3, P_POW = 4, P_ATOM = 5;

function sp() {
  const r = rnd();
  return r < 0.6 ? "" : r < 0.88 ? " " : r < 0.93 ? "  " : r < 0.96 ? "\t" : r < 0.98 ? "\n" : "\r\n";
}
const wrap = (x, min) => (x.p < min ? { t: `(${sp()}${x.t}${sp()})`, p: P_ATOM }
  : chance(0.06) ? { t: `(${x.t})`, p: P_ATOM } : x);
function leaf() {
  return chance(0.5) ? { t: pick(NUM_POOL), p: P_ATOM } : { t: pick(NAME_POOL), p: P_ATOM };
}
function gen(depth) {
  const r = rnd();
  if (depth <= 0 || r < 0.22) return leaf();
  if (r < 0.34) {                                   // unary
    const a = wrap(gen(depth - 1), P_UN);
    return { t: (chance(0.8) ? "-" : "+") + sp() + a.t, p: P_UN };
  }
  if (r < 0.62) {                                   // + - * /
    const op = pick(["+", "-", "*", "/"]), p = op === "+" || op === "-" ? P_ADD : P_MUL;
    const l = wrap(gen(depth - 1), p), rr = wrap(gen(depth - 1), p + 1);
    return { t: l.t + sp() + op + sp() + rr.t, p };
  }
  if (r < 0.78) {                                   // ^ (base: an atom; exponent: unary level)
    const base = wrap(gen(depth - 1), P_ATOM);
    const ex = chance(0.3) ? { t: (chance(0.3) ? "-" : "") + pick(EXP_POOL), p: P_UN } : wrap(gen(depth - 1), P_UN);
    return { t: base.t + sp() + (chance(0.25) ? "**" : "^") + sp() + ex.t, p: P_POW };
  }
  const [fn, ar] = pick(FN);                        // call
  const n = ar > 0 ? ar : 1 + ri(4);
  const args = Array.from({ length: n }, () => gen(depth - 1).t);
  return { t: fn + (chance(0.1) ? " " : "") + "(" + sp() + args.join(sp() + "," + sp()) + sp() + ")", p: P_ATOM };
}

const MUT_INSERT = [")", "(", ",", "*", "^", "**", "@", "#", "$", ".", "e", '"', "5", "k", " ", MU1, MU2,
  "é", "€", " ", "😀", "ms", "1.2.3", "abs", "foo", "pi(", "()", "--", "1e", "2e3k",
  "+", "-", "/", "\v", "\f", " ", "0x1f", "1_000", "Inf", "NaN", "nan", "inf", "'", "[", "]", "!", "%",
  "=", "<", "&", "|", "~", "`", "\\", "{", "}", ";", ":", "?", "٣", "E", "\ud83d"];
function mutate(t) {
  const k = 1 + ri(2);
  for (let i = 0; i < k; i++) {
    const at = ri(t.length + 1), r = rnd();
    if (r < 0.45) t = t.slice(0, at) + pick(MUT_INSERT) + t.slice(at);
    else if (r < 0.7 && t.length) t = t.slice(0, at) + t.slice(at + 1);
    else if (r < 0.8) t = t.slice(0, at);
    else if (r < 0.9 && t.length > 1) { const j = Math.min(at, t.length - 2); t = t.slice(0, j) + t[j + 1] + t[j] + t.slice(j + 2); }
    else t = t.slice(0, at) + t.slice(ri(t.length + 1), ri(t.length + 1)) + t.slice(at);
  }
  return t;
}

const HAND = ["", " ", "\t\r\n", "()", "(", ")", "1 2", "1,2", "abs", "abs()", "abs(1,2)", "pow(1)", "pow(1,2,3)",
  "min()", "max()", "min(1)", "max(snan, 1)", "min(1, snan)", "5ms", "2e", "1.2.3", "2e3k", "1e5e", ".e5", "1..2",
  "..5", "1.e3", "1.k", "3" + MU1, "3" + MU2, "3" + MU1 + "m", "5 k", "5k k", "k", "M", '""', '"', '"m', 'm"',
  '"odd name"', "odd name", '"abs"(1)', "abs (1)", "abs\n(1)", "pi", "pi()", '"pi"', "pi^2", "-pi^2", "(-2)^0.5",
  "-2^0.5", "2^-1", "2^-1^2", "2**3**2", "2^3^2", "-2^2", "(-2)^2", "2^--2", "--2", "+-+2", "1/0", "-1/0", "0/0",
  "1/-0", "-0", "0*-1", "1e308*10", "1e-320/1e10", "sqrt(-1)", "ln(0)", "ln(-1)", "log10(0)", "exp(710)",
  "exp(-746)", "pow(0,-1)", "pow(-0,-1)", "pow(-8, 1/3)", "1^snan", "snan^0", "pow(snan, 0)", "pow(1, snan)",
  "(-1)^(1/0)", "(-1)^(-1/0)", "pow(-1, 1e309)", "0^0", "lin2db(0)", "lin2db(-1)", "lin2db(snan)", "db2lin(1e9)",
  "db2lin(-1e9)", "round(-0.5)", "round(0.49999999999999994)", "round(2.5)", "floor(-0.5)", "ceil(-0.5)",
  "1/ceil(-0.5)", "1/round(-0.4)", "1/min(-0, 0)", "1/min(0, -0)", "1/max(-0, 0)", "1/max(0, -0)",
  "exp(1/min(0, -0))", "exp(1/min(-0, 0))", "exp(-1/max(0, -0))", "vinf^0.5", "(-0)^0.5", "pow(-0, 0.5)",
  "1/(-1/0)^0.5", "exp(-1/(-0)^0.5)", "vinf^2.5", "vinf^-0.5", "(-1/0)^-0.5", "log(exp(7n))", "1/abs(-0)", "1/-szero", "1/snz", "1/(m*0)", "1/min(m, 0)", "1/max(m*-0, 0)",
  "m - n", "n - m", "m*n", "m/n", "m/m", "n/n", "va - max", "max(va) - max", "max(max)", "max(max, va)",
  '"max"(1)', "max (va, 1)", "va^2", "va^-1", "va^-0.5", "va^+2", "va^--2", "pow(va, 2)", "pow(va, -2)",
  "va^(2)", "va^b", "abs(va)", "abs(1, va)", "min(1, va, n)", "lin2db(n)", "lin2db(vb)", "lin2db(s0)",
  "db2lin(va)", "db2lin(vinf)", "db2lin(\"odd name\")", "db2lin(n)", "db2lin(1)", "va + \"odd name\"",
  "\"odd name\" + va", "\"odd name\" - \"odd name\"", "va - va", "va + 1", "1 + va", "1 - va", "va / s0",
  "s0 / va", "1 / s0", "s0 * va", "t", "t * 1e9", "t + a", "a", "b", "a + b", "b + a", "a*b - b*a",
  "\"1st\"", "1st", "\"wl.nm\" - 1550", "wl.nm", "ib / 2", "ib * 1e308", "big * big", "big / tiny", "tiny * 1e300",
  "tiny / 2", "-tiny", "vinf - vinf", "vinf * 0", "1/vinf", "snan + 1", "x", "\"\" + 1", "a +", "+ a",
  "a b", "(a)(b)", "a(1)", "foo(1)", "e", "e1", "1e", "1E5", "1e+5", "1e-5k", "0.5e-3m", "1" + MU1 + MU2,
  "µ", "μ1", "1 + 1", "1 +1", "\"😀\" + 1", "\"😀\" + @", "😀",
  "1 + \"a b\" @", "abs(a,)", "abs(,a)", "min(a,,b)", "((a)", "(a))", "a^", "^a", "a**", "a***b", "a^^b", "a*/b"];
for (const k of [63, 64, 65, 66, 100, 150, 180, 200, 300, 499]) {
  HAND.push("(".repeat(k) + "1" + ")".repeat(k));
  HAND.push("-".repeat(k) + "1");
  HAND.push("2^".repeat(k) + "1");
  if (5 * k + 1 <= 1000) HAND.push("abs(".repeat(k) + "1" + ")".repeat(k));
}

// ============================================================ shrinking
const PREC = { "+": 1, "-": 1, "*": 2, "/": 2 };
function printAst(nd) {
  switch (nd.type) {
    case "num": return { t: nd.text, p: P_ATOM };
    case "name": return { t: nd.quoted ? `"${nd.name}"` : nd.name, p: P_ATOM };
    case "unary": { const a = printAst(nd.arg); return { t: nd.op + (a.p < P_UN ? `(${a.t})` : a.t), p: P_UN }; }
    case "call": return { t: `${nd.fn}(${nd.args.map((x) => printAst(x).t).join(", ")})`, p: P_ATOM };
    default: {
      const l = printAst(nd.left), r = printAst(nd.right);
      if (nd.op === "^") return { t: `${l.p < P_ATOM ? `(${l.t})` : l.t}^${r.p < P_UN ? `(${r.t})` : r.t}`, p: P_POW };
      const p = PREC[nd.op];
      return { t: `${l.p < p ? `(${l.t})` : l.t} ${nd.op} ${r.p <= p ? `(${r.t})` : r.t}`, p };
    }
  }
}
// every AST with one node replaced by something simpler
function astVariants(root) {
  const out = [];
  const LEAVES = ["1", "0", "2", "-0"].map((t) => (t === "-0" ? { type: "unary", op: "-", arg: { type: "num", text: "0" } }
    : { type: "num", text: t }));
  const walk = (nd, rebuild) => {
    const repl = [];
    if (nd.type === "unary") repl.push(nd.arg);
    if (nd.type === "bin") repl.push(nd.left, nd.right);
    if (nd.type === "call") {
      repl.push(...nd.args);
      if (nd.args.length > 1) nd.args.forEach((_, i) => repl.push({ ...nd, args: nd.args.filter((__, j) => j !== i) }));
    }
    if (nd.type !== "num") repl.push(...LEAVES);
    for (const r of repl) out.push(rebuild(r));
    if (nd.type === "unary") walk(nd.arg, (x) => rebuild({ ...nd, arg: x }));
    if (nd.type === "bin") {
      walk(nd.left, (x) => rebuild({ ...nd, left: x }));
      walk(nd.right, (x) => rebuild({ ...nd, right: x }));
    }
    if (nd.type === "call") nd.args.forEach((a, i) => walk(a, (x) => rebuild({ ...nd, args: nd.args.map((y, j) => (j === i ? x : y)) })));
  };
  walk(root, (x) => x);
  return out.map((a) => printAst(a).t);
}
const weight = (t) => t.replace(/[ \t\r\n]/g, "").length + (t.length - t.replace(/[ \t\r\n]/g, "").length) * 0.01;
function candidates(text) {
  const c = new Set();
  try { for (const v of astVariants(E.parseExpr(text))) c.add(v); } catch (e) { /* text-level only */ }
  try { c.add(printAst(E.parseExpr(text)).t); } catch (e) { /* not parseable */ }
  if (text.length <= 400) {
    for (let i = 0; i < text.length; i++) c.add(text.slice(0, i) + text.slice(i + 1));
    for (let i = 0; i < text.length; i++) for (const L of [2, 3, 5, 8]) c.add(text.slice(0, i) + text.slice(i + L));
  } else {
    c.add(text.slice(1, -1)); c.add(text.slice(2, -2)); c.add(text.slice(10, -10)); c.add(text.slice(50, -50));
  }
  c.delete(text);
  return [...c].filter((t) => weight(t) < weight(text)).sort((a, b) => weight(a) - weight(b)).slice(0, 600);
}

// ============================================================ main
const T0 = Date.now();
const findings = [];          // {part, cat, text, detail}
const synPath = path.join(TMP, "syn.nc"), edgePath = path.join(TMP, "edge.nc");
fs.writeFileSync(path.join(TMP, "mk.py"), MK_PY);
fs.writeFileSync(path.join(TMP, "probe.py"), PROBE_PY);
{
  const r = runPy([path.join(TMP, "mk.py"), synPath, edgePath]);
  if (!check("synthetic NetCDF-3 files written", r.status === 0 && fs.existsSync(synPath) && fs.existsSync(edgePath), r.out)) {
    summary("expr_parity"); process.exit(1);
  }
}
const dsSyn = await loadDataset(synPath), dsEdge = await loadDataset(edgePath);
check("synthetic dims a(3), b(4)", dsSyn.dims.a === 3 && dsSyn.dims.b === 4, dsSyn.dims);

// any generated script will do for the helpers (CONFIG is irrelevant to them)
const helperScript = path.join(TMP, "helpers.py");
fs.writeFileSync(helperScript, P.buildReportScript(reportProject([{ file: "syn.nc", v: "m", lineDim: "b", xsrc: "coord" }], []),
  { generatedAt: "2026-10-02T00:00:00.000Z" }), "utf8");
const py = new PyProbe(helperScript);
const DS = { syn: dsSyn, edge: dsEdge };
try {
  await py.req({ op: "open", key: "syn.nc", path: synPath });
  await py.req({ op: "open", key: "edge.nc", path: edgePath });
} catch (e) {
  check("python probe starts", false, e.message);
  summary("expr_parity"); process.exit(1);
}

const VALUE_CATS = new Set(["raw-value", "formula-value"]);
let noise = 0;
const noiseEx = [], noiseTexts = new Set();
async function evalBoth(which, texts) {
  const key = which === "syn" ? "syn.nc" : "edge.nc";
  const res = (await py.req({ op: "exprs", key, exprs: texts })).results;
  const out = texts.map((t, i) => {
    const js = jsOne(DS[which], t);
    return { text: t, js, py: res[i], diffs: compareExpr(js, res[i]) };
  });
  // value mismatches outside + - * /: re-check operation by operation
  const need = out.filter((r) => !r.js.exact && r.diffs.some((d) => VALUE_CATS.has(d.cat)));
  if (need.length) {
    const plans = need.map((r) => { try { return localPlan(DS[which], r.text); } catch (e) { return null; } });
    const reqs = plans.flatMap((p) => (p ? p.map((o) => o.req) : []));
    const ans = reqs.length ? (await py.req({ op: "apply", ops: reqs })).results : [];
    let k = 0;
    need.forEach((r, i) => {
      if (!plans[i]) return;
      let bad = "";
      for (const o of plans[i]) { const a = ans[k++]; if (!bad) bad = localDiff(o, a); }
      if (bad) {
        for (const d of r.diffs) if (VALUE_CATS.has(d.cat)) d.detail += `; ${bad}`;
      } else {
        noise++;
        noiseTexts.add(r.text);
        if (noiseEx.length < 3) noiseEx.push(`${JSON.stringify(r.text)}: ${r.diffs.filter((d) => VALUE_CATS.has(d.cat)).map((d) => d.detail).join("; ")}`);
        r.diffs = r.diffs.filter((d) => !VALUE_CATS.has(d.cat));
      }
    });
  }
  return out;
}

async function shrink(which, text, cat) {
  let cur = text;
  for (let round = 0; round < 60; round++) {
    const cands = candidates(cur);
    if (!cands.length) break;
    let next = null;
    for (let i = 0; i < cands.length && !next; i += 150) {
      const rs = await evalBoth(which, cands.slice(i, i + 150));
      const hit = rs.find((r) => r.diffs.some((d) => d.cat === cat));
      if (hit) next = hit.text;
    }
    if (!next) break;
    cur = next;
  }
  const [r] = await evalBoth(which, [cur]);
  return { text: cur, detail: (r.diffs.find((d) => d.cat === cat) || {}).detail };
}

// ---- part 1a: random + mutated + hand-made expressions on the synthetic file
const texts = [];
for (let i = 0; i < N_RANDOM; i++) texts.push(gen(1 + ri(5)).t);
const nValid = texts.length;
for (let i = 0; i < Math.round(N_RANDOM / 4); i++) texts.push(mutate(pick(texts.slice(0, nValid))));
texts.push(...HAND);
const results = [];
for (let i = 0; i < texts.length; i += 500) results.push(...await evalBoth("syn", texts.slice(i, i + 500)));
const jsAccepted = results.filter((r) => !r.js.parse).length;
const cover = { ops: new Set(), fns: new Set(), si: new Set(), quoted: 0, pow2: 0, neg: 0 };
for (const r of results) {
  try {
    const ast = E.parseExpr(r.text);
    const w = (nd) => {
      if (nd.type === "bin") { cover.ops.add(nd.op); if (nd.op === "^" && nd.right.type === "bin" && nd.right.op === "^") cover.pow2++; w(nd.left); w(nd.right); }
      else if (nd.type === "unary") { cover.ops.add("u" + nd.op); if (nd.op === "-" && nd.arg.type === "bin" && nd.arg.op === "^") cover.neg++; w(nd.arg); }
      else if (nd.type === "call") { cover.fns.add(nd.fn); nd.args.forEach(w); }
      else if (nd.type === "num") { const s = nd.text.slice(-1); if (hasOwn(E.SI, s)) cover.si.add(s); }
      else if (nd.type === "name" && nd.quoted) cover.quoted++;
    };
    w(ast);
  } catch (e) { /* invalid */ }
}
console.log(`part 1a: ${texts.length} expressions (${nValid} random, ${texts.length - nValid - HAND.length} mutated, `
  + `${HAND.length} hand-made), ${jsAccepted} parse in JS; ops ${[...cover.ops].sort().join(" ")}; `
  + `functions ${cover.fns.size}/${FN.length}; SI ${[...cover.si].join("")}; quoted ${cover.quoted}; a^b^c ${cover.pow2}; -a^b ${cover.neg}`);
check("part 1a: >= 2000 random expressions", nValid >= 2000, nValid);
check("part 1a: every operator covered", ["+", "-", "*", "/", "^", "u-", "u+"].every((o) => cover.ops.has(o)), [...cover.ops]);
check("part 1a: every function covered", cover.fns.size === FN.length, [...cover.fns]);
check("part 1a: every SI suffix covered", Object.keys(E.SI).every((s) => cover.si.has(s)), [...cover.si]);
check("part 1a: python answered every expression", results.every((r) => r.py && r.py.formula), "");

// group by category; shrink the smallest example of each
async function report(part, which, rs) {
  const byCat = new Map();
  for (const r of rs) for (const d of r.diffs) {
    if (!byCat.has(d.cat)) byCat.set(d.cat, []);
    byCat.get(d.cat).push({ text: r.text, detail: d.detail });
  }
  for (const [cat, list] of byCat) {
    list.sort((a, b) => weight(a.text) - weight(b.text));
    // a few examples with DIFFERENT messages (digits ignored), smallest first
    const seen = new Set(), ex = [];
    for (const e of list) {
      const sig = String(e.detail).replace(/[-\d.e+]+|Infinity/g, "#");
      if (!seen.has(sig) && ex.length < 6) { seen.add(sig); ex.push(e); }
    }
    const min = await shrink(which, ex[0].text, cat);
    findings.push({ part, cat, count: list.length, text: min.text, detail: min.detail, examples: ex });
    console.log(`MISMATCH ${part} [${cat}] x${list.length}  minimal: ${JSON.stringify(min.text)}  -> ${min.detail}`);
    for (const e of ex) console.log(`    e.g. ${JSON.stringify(e.text).slice(0, 160)}  -> ${String(e.detail).split("\n")[0]}`);
    check(`${part}: no '${cat}' mismatch`, false, `${list.length} case(s), minimal ${JSON.stringify(min.text)}: ${min.detail}`);
  }
  if (!byCat.size) check(`${part}: JS and Python agree on all ${rs.length} expressions`, true);
}
console.log(`part 1a: ${noise} value difference(s) outside + - * / traced to 1-4 ulp library rounding `
  + `(every operation agrees on the same inputs)${noiseEx.map((e) => "\n    " + e).join("")}`);
await report("part 1a (syn)", "syn", results);

// ---- part 1b: edge file (names / units / storage)
const EDGE = ["pi", "pi^2", '"pi"', "pi + t", "tm", "tm/60", "nchar", "nchar + 1", "label", "label + 1", "x - bom",
  "bom - x", "x - us1", "us1 - x", "lin2db(db2lin(bom))", "db2lin(us1)", "sc", "sc*2", "x", "t", "t*1e9",
  '"pwr µW"', '"pwr µW" * x', "fv", "fv*2"];
const edgeRes = await evalBoth("edge", EDGE);
await report("part 1b (edge file)", "edge", edgeRes);

// ---- part 1c: end-to-end: the generated script with --dump-derived (all formulas)
{
  const fdefs = texts.map((t, i) => FM(`f${i}`, "syn.nc", t));
  const proj = reportProject([{ file: "syn.nc", v: "m", lineDim: "b", xsrc: "coord" }], fdefs);
  const script = P.buildReportScript(proj, { generatedAt: "2026-10-02T00:00:00.000Z" });
  const sp1 = path.join(TMP, "e2e_syn.py"), dj = path.join(TMP, "e2e_syn.json");
  fs.writeFileSync(sp1, script, "utf8");
  const r = runPy([sp1, "--data-dir", TMP, "--out", path.join(TMP, "e2e_syn.pdf"), "--dump-derived", dj]);
  fs.writeFileSync(path.join(TMP, "e2e_syn.out.txt"), r.out);
  if (check("part 1c: script ran (exit 0)", r.status === 0, r.out.slice(-2000))) {
    const dump = JSON.parse(fs.readFileSync(dj, "utf8"))["syn.nc"] || {};
    const bad = [];
    results.forEach((res, i) => {
      const jf = res.js.formula, pv = dump[`f${i}`];
      let why = "";
      if (!!jf.error !== !pv) why = `accept: js ${jf.error || "ok"} | script ${pv ? "computed" : "not computed"}`;
      else if (pv) {
        if (JSON.stringify(jf.dims) !== JSON.stringify(pv.dims)) why = `dims js ${JSON.stringify(jf.dims)} | script ${JSON.stringify(pv.dims)}`;
        else if (jf.units !== pv.units) why = `units js ${JSON.stringify(jf.units)} | script ${JSON.stringify(pv.units)}`;
        else if (!noiseTexts.has(res.text)) why = firstDiff(jf.data, pv.data.map((v) => (v === null ? NaN : v)), res.js.exact, 1e-12);
      }
      if (why) bad.push({ text: res.text, why });
    });
    bad.sort((a, b) => weight(a.text) - weight(b.text));
    for (const b of bad.slice(0, 8)) console.log(`MISMATCH part 1c (--dump-derived) ${JSON.stringify(b.text).slice(0, 160)} -> ${b.why}`);
    if (bad.length) findings.push({ part: "part 1c", cat: "dump-derived", count: bad.length, text: bad[0].text, detail: bad[0].why });
    check(`part 1c: --dump-derived == registerDerived for ${results.length} formulas`, !bad.length,
      bad.length ? `${bad.length} differ, e.g. ${JSON.stringify(bad[0].text)}: ${bad[0].why}` : "");
  }
}

// ---- part 1d: random reduce defs with expression windows (synthetic file)
{
  const WNUM = ["0", "1", "1.5", "2", "3", "10", "15", "25", "35", "40", "1550.15", "1550.3", "5", "0.5", "-1",
    "1e3", "20m", "0.02k", "1e-9", "0"];
  const WNAME = ["va", "a", "s0", "sneg", "snan", "szero", "t", "vinf", '"odd name"', '"1st"', "max", "pi", "snz"];
  const wexpr = (d) => {
    const r = rnd();
    if (d <= 0 || r < 0.35) return chance(0.03) ? pick(["b", "m", "nope", "1 +", ""]) : (chance(0.55) ? pick(WNUM) : pick(WNAME));
    if (r < 0.75) return `${wexpr(d - 1)} ${pick(["+", "-", "*", "/"])} ${wexpr(d - 1)}`;
    if (r < 0.85) return `-(${wexpr(d - 1)})`;
    if (r < 0.92) return `${pick(["abs", "floor", "round", "sqrt", "ln", "db2lin"])}(${wexpr(d - 1)})`;
    return `${pick(["min", "max", "pow"])}(${wexpr(d - 1)}, ${wexpr(d - 1)})`;
  };
  const SRC = [["m", "b"], ["n", "b"], ["m", "a"], ["n", "a"], ["vb", "b"], ["big", "b"]];
  const XS = ["index", "coord", "var:wl.nm", "var:ib", "var:b", "var:vb", "var:tiny"];
  const defs = [];
  for (let i = 0; i < 600; i++) {
    const [src, over] = pick(SRC), mode = pick(["none", "range", "range", "center", "center"]);
    const region = mode === "none" ? "inside" : pick(["inside", "outside", "outside_within"]);
    const w = { mode };
    if (mode === "range") { w.lo = wexpr(2); w.hi = wexpr(2); if (region === "outside_within" || chance(0.2)) { w.lo2 = wexpr(2); w.hi2 = wexpr(2); } }
    if (mode === "center") { w.center = wexpr(2); w.halfwidth = wexpr(2); if (region === "outside_within" || chance(0.2)) w.halfwidth2 = wexpr(2); }
    const xs = over === "b" ? pick(XS) : pick(["index", "coord"]);
    defs.push(RD(`w${i}`, "syn.nc", src, over, xs, w, region,
      pick(["max", "min", "mean", "median", "std", "sum", "integral", "count", "argmax_x", "argmin_x"]), pick(["auto", "yes", "no"])));
  }
  const pyRes = (await py.req({ op: "derive", key: "syn.nc", defs })).results;
  const jsRes = new Map();
  for (let i = 0; i < defs.length; i += 200) {
    const chunk = defs.slice(i, i + 200);
    const st = D.registerDerived(dsSyn, chunk);
    for (const d of chunk) {
      const s = st.get(d.name), v = dsSyn.vars[d.name];
      jsRes.set(d.name, s && s.ok ? { dims: v.dims.slice(), units: String(v.attrs.units), data: Float64Array.from(v.data) }
        : { error: s ? s.error : "no status" });
    }
  }
  D.unregisterDerived(dsSyn);
  const bad = [];
  let ok = 0;
  for (const d of defs) {
    const j = jsRes.get(d.name), p = pyRes[d.name];
    let why = "";
    if (!!j.error !== !!p.error) why = `accept: js ${j.error || "ok"} | py ${p.error || "ok"}`;
    else if (!j.error) {
      ok++;
      if (JSON.stringify(j.dims) !== JSON.stringify(p.dims)) why = `dims js ${JSON.stringify(j.dims)} | py ${JSON.stringify(p.dims)}`;
      else if (j.units !== p.units) why = `units js ${JSON.stringify(j.units)} | py ${JSON.stringify(p.units)}`;
      else why = firstDiff(j.data, p.data, false, 1e-9);
    }
    if (why) bad.push({ d, why });
  }
  console.log(`part 1d: ${defs.length} random reduce defs, ${ok} computed by both, ${bad.length} mismatches`);
  for (const b of bad.slice(0, 10)) console.log(`MISMATCH part 1d ${JSON.stringify({ src: b.d.src, over: b.d.over, xsrc: b.d.xsrc, window: b.d.window, region: b.d.region, stat: b.d.stat, db: b.d.db })} -> ${b.why}`);
  if (bad.length) findings.push({ part: "part 1d", cat: "window", count: bad.length, text: JSON.stringify(bad[0].d), detail: bad[0].why });
  check("part 1d: random expression windows agree (rel 1e-9)", !bad.length, bad.length ? `${bad.length} differ` : "");
  check("part 1d: enough windows computed by both", ok >= 200, ok);
}

// ---- part 1e: def-level cases (names that collide with dims / variables / pi /
// functions, failed dependencies, cycles, chains, unused or odd window fields)
{
  const S = "syn.nc";
  const w0 = WIN();
  const CASES = [
    ["def named like a dimension, used by another def", [FM("a", S, "1"), FM("ua", S, "a + 1")]],
    ["def named like a real variable, used by another def", [FM("m", S, "1"), FM("um", S, "m*2")]],
    ["failed def named pi, used by another def", [FM("pi", S, "1 +"), FM("upi", S, "pi*2")]],
    ["def named pi", [FM("pi", S, "3"), FM("upi2", S, "pi*2")]],
    ["def named like a function", [FM("ceil", S, "va*2"), FM("uc", S, "ceil + ceil(va)")]],
    ["self reference", [FM("selfref", S, "selfref + 1")]],
    ["cycle", [FM("c1", S, "c2 + 1"), FM("c2", S, "c1 + 1"), FM("c3", S, "c1 * 0 + 5")]],
    ["duplicate name", [FM("dup", S, "1"), FM("dup", S, "2"), FM("udup", S, "dup*3")]],
    ["quoted def name", [FM("my snr", S, "va - 1"), FM("use", S, '"my snr" * 2')]],
    ["window centered on a formula", [FM("cen", S, "a*10 + 15"),
      RD("pk", S, "m", "b", "coord", { mode: "center", center: "cen", halfwidth: "6" }, "inside", "max"), FM("pkd", S, "pk - va")]],
    ["unused window fields hold junk", [RD("uw", S, "m", "b", "index", { mode: "center", center: "1", halfwidth: "1",
      lo: "nope +", hi: "c9", halfwidth2: "zz" }, "inside", "max")]],
    ["cycle only through an unused window field", [RD("cy1", S, "m", "b", "index", { mode: "center", center: "1",
      halfwidth: "1", lo: "cy2", halfwidth2: "cy2" }, "inside", "max"), FM("cy2", S, "cy1 + 1")]],
    ["window uses a failed def", [FM("bad", S, "1 +"), RD("wb", S, "m", "b", "index", { mode: "center", center: "bad", halfwidth: "1" }, "inside", "max")]],
    ["numbers in a new-format window", [{ ...RD("nw", S, "m", "b", "index", {}, "inside", "max"), window: { ...w0, mode: "range", lo: 1, hi: 2.5 } }]],
    ["var: center under mode center", [{ ...RD("vc", S, "m", "b", "index", {}, "inside", "max"),
      window: { ...w0, mode: "center", center: "var:va", halfwidth: "1" } }]],
    ["legacy relative window", [{ ...RD("lr", S, "m", "b", "coord", {}, "inside", "max"),
      window: { mode: "relative", lo: null, hi: null, lo2: null, hi2: null, center: "var:va", k: 2, offset: 0.5, halfwidth: -1, halfwidth2: null } }]],
    ["window over dims the result lacks", [RD("wd", S, "m", "b", "index", { mode: "center", center: "b", halfwidth: "1" }, "inside", "max")]],
    ["time units through a derived var", [FM("tt", S, "t"), FM("tt2", S, "tt*1")]],
    ["0-D formula", [FM("k0", S, "2*pi"), FM("k1", S, "k0 + va")]],
  ];
  const py2 = new PyProbe(helperScript);
  await py2.req({ op: "open", key: S, path: synPath });
  for (const [id, defs] of CASES) {
    const pr = (await py2.req({ op: "derive", key: S, defs })).results;
    const st = D.registerDerived(dsSyn, defs);
    const names = [...new Set(defs.map((d) => d.name))];
    const diffs = [];
    for (const n of names) {
      const s = st.get(n), p = pr[n], v = dsSyn.vars[n];
      if (!!(s && s.ok) === !!p.error) { diffs.push(`'${n}': js ${s && s.ok ? "ok" : (s ? s.error : "no status")} | py ${p.error || "ok"}`); continue; }
      if (p.error) continue;
      if (JSON.stringify(v.dims) !== JSON.stringify(p.dims)) diffs.push(`'${n}' dims js ${JSON.stringify(v.dims)} | py ${JSON.stringify(p.dims)}`);
      else if (String(v.attrs.units) !== p.units) diffs.push(`'${n}' units js ${JSON.stringify(v.attrs.units)} | py ${JSON.stringify(p.units)}`);
      else { const d = firstDiff(Array.from(v.data), p.data, false, 1e-9); if (d) diffs.push(`'${n}' values ${d}`); }
    }
    D.unregisterDerived(dsSyn);
    if (diffs.length) {
      console.log(`MISMATCH part 1e [${id}] ${JSON.stringify(defs.map((d) => (d.kind === "formula" ? { [d.name]: d.expr } : { [d.name]: d.window })))} -> ${diffs.join("; ")}`);
      findings.push({ part: "part 1e", cat: id, text: JSON.stringify(defs.map((d) => d.name)), detail: diffs.join("; ") });
    }
    check(`part 1e: ${id}`, !diffs.length, diffs.join("; "));
  }
  await py2.close();
}
await py.close();

// ============================================================ part 2: real files
const DA = "darpa.nc", SB = "sidebands.nc", PC = "powercal_hdf5.nc";
const LEGACY = (name, win, stat) => ({ name, file: DA, kind: "reduce", units: "", description: "", src: "spectrums",
  over: "TraceIndex", xsrc: "var:frequencies", window: win, region: "inside", stat, db: "auto" });
const DF = (name, win, region, stat, db) => RD(name, DA, "spectrums", "TraceIndex", "var:frequencies", win, region, stat, db);
const REAL_DEFS = [
  DF("pk_rel", { mode: "center", center: "stimulusFrequency", halfwidth: "0.01*stimulusFrequency" }, "inside", "max"),
  DF("pk_rbw", { mode: "center", center: "stimulusFrequency", halfwidth: "3*ResolutionBWs" }, "inside", "max"),
  DF("fl_ow", { mode: "center", center: "stimulusFrequency", halfwidth: "3*ResolutionBWs", halfwidth2: "0.2*stimulusFrequency" }, "outside_within", "mean"),
  DF("fl_med", { mode: "center", center: "stimulusFrequency", halfwidth: "3*ResolutionBWs", halfwidth2: "0.2*stimulusFrequency" }, "outside_within", "median"),
  DF("ax_range", { mode: "range", lo: "0.9*stimulusFrequency", hi: "1.1*stimulusFrequency" }, "inside", "argmax_x"),
  DF("md_rev", { mode: "range", lo: "1.1*stimulusFrequency", hi: "0.9*stimulusFrequency" }, "inside", "median"),
  DF("h2", { mode: "center", center: "2*stimulusFrequency", halfwidth: "5*ResolutionBWs" }, "inside", "max"),
  DF("h3off", { mode: "center", center: "3*stimulusFrequency + 50k", halfwidth: "100k" }, "inside", "max"),
  DF("offneg", { mode: "center", center: "stimulusFrequency - 1.5M", halfwidth: "200k" }, "inside", "max"),
  DF("cnt_out", { mode: "center", center: "stimulusFrequency", halfwidth: "2*VideoBWs" }, "outside", "count"),
  DF("integ", { mode: "center", center: "stimulusFrequency", halfwidth: "0.005*stimulusFrequency" }, "inside", "integral"),
  DF("sd", { mode: "range", lo: "stimulusFrequency - 10*ResolutionBWs", hi: "stimulusFrequency + 10*ResolutionBWs" }, "inside", "std"),
  DF("trace_c", { mode: "center", center: "stimulusFrequency*(1 + trace/100)", halfwidth: "1M" }, "inside", "max"),
  DF("undef", { mode: "center", center: "stimulusFrequency/(trace - 1)", halfwidth: "1M" }, "inside", "max"),
  DF("undef_cnt", { mode: "center", center: "stimulusFrequency/(trace - 1)", halfwidth: "1M" }, "outside", "count"),
  DF("mx_hw", { mode: "center", center: "stimulusFrequency", halfwidth: "max(3*ResolutionBWs, 0.002*stimulusFrequency)" }, "inside", "sum"),
  DF("pow_rng", { mode: "range", lo: "stimulusFrequency - 2^20", hi: "stimulusFrequency + pow(2, 20)" }, "inside", "mean", "no"),
  DF("sqrt_hw", { mode: "center", center: '"stimulusFrequency"', halfwidth: "sqrt(ResolutionBWs*VideoBWs)*10" }, "inside", "min"),
  DF("amp_hw", { mode: "center", center: "stimulusFrequency", halfwidth: "stimulusAmp*1e9", halfwidth2: "stimulusAmp*3e9" }, "outside_within", "argmin_x"),
  DF("rbw_ow_rng", { mode: "range", lo: "stimulusFrequency - 3*ResolutionBWs", hi: "stimulusFrequency + 3*ResolutionBWs",
    lo2: "0.5*stimulusFrequency", hi2: "1.5*stimulusFrequency" }, "outside_within", "max"),
  RD("idx_rng", DA, "spectrums", "TraceIndex", "index", { mode: "range", lo: "0.1k", hi: "0.2k" }, "inside", "max"),
  RD("coord_rng", DA, "spectrums", "TraceIndex", "coord", { mode: "range", lo: "300", hi: "300 + 5*trace" }, "inside", "mean"),
  FM("snr", DA, "pk_rel - fl_ow"),
  FM("nf", DA, "fl_ow - 10*log10(ResolutionBWs)"),
  FM("tot", DA, "lin2db(db2lin(pk_rel) + db2lin(pk_rbw))"),
  FM("rel_l", DA, "pk_rel - laswrPowers"),
  FM("rnd", DA, "round(pk_rel*10)/10"),
  FM("adiff", DA, "abs(pk_rel - pk_rbw)"),
  FM("dims1", DA, "ResolutionBWs + trace"),
  FM("dims2", DA, "trace + ResolutionBWs"),
  FM("tix", DA, "TraceIndex^2 / 1k"),
  FM("specnorm", DA, "spectrums - laswrPowers"),
  RD("pk_norm", DA, "specnorm", "TraceIndex", "var:frequencies", { mode: "center", center: "stimulusFrequency", halfwidth: "3*ResolutionBWs" }, "inside", "max"),
  DF("ax", { mode: "range", lo: "0.5*stimulusFrequency", hi: "1.5*stimulusFrequency" }, "inside", "argmax_x"),
  DF("pk_at_ax", { mode: "center", center: "ax", halfwidth: "3*ResolutionBWs" }, "inside", "max"),
  FM("ratio", DA, "VideoBWs/ResolutionBWs"),
  FM("cplx", DA, "max(pk_rel, pk_rbw, fl_ow) - min(pk_rel, -200)"),
  LEGACY("leg_rel", { mode: "relative", lo: null, hi: null, lo2: null, hi2: null, center: "coord:stimulusFrequency",
    k: 2, offset: -1e6, halfwidth: -5e5, halfwidth2: null }, "max"),
  LEGACY("leg_fix", { mode: "fixed", lo: 2.9e7, hi: 3.1e7, lo2: null, hi2: null, center: "", k: 1, offset: 0,
    halfwidth: null, halfwidth2: null }, "mean"),
  // must fail in both
  DF("bad_dim", { mode: "center", center: "frequencies", halfwidth: "1M" }, "inside", "max"),
  DF("bad_name", { mode: "center", center: "stimulusFreq", halfwidth: "1M" }, "inside", "max"),
  DF("bad_empty", { mode: "center", center: "stimulusFrequency", halfwidth: "" }, "inside", "max"),
  DF("bad_over", { mode: "range", lo: "TraceIndex", hi: "2" }, "inside", "max"),
  DF("bad_syntax", { mode: "center", center: "stimulusFrequency", halfwidth: "3*" }, "inside", "max"),
  FM("bad_f", DA, "pk_rel - "),
  FM("dep_bad", DA, "bad_name + 1"),

  RD("sb_pump", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "center", center: "pump_nm", halfwidth: "0.05" }, "inside", "max"),
  RD("sb_low_pk", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "center", center: "sb_low_nm", halfwidth: "20m" }, "inside", "max"),
  RD("sb_floor", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "center", center: "pump_nm", halfwidth: "0.05", halfwidth2: "0.6" }, "outside_within", "median"),
  RD("sb_rng", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "range", lo: "pump_nm - 0.5", hi: "pump_nm - 0.1" }, "inside", "mean"),
  RD("sb_rng_ow", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "range", lo: "pump_nm - 0.05", hi: "pump_nm + 0.05",
    lo2: "pump_nm + 0.6", hi2: "pump_nm - 0.6" }, "outside_within", "integral"),
  RD("sb_freqc", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "center", center: "pump_nm + freq*1e-3", halfwidth: "5e-3*(1 + sb_resolved)" }, "inside", "argmax_x"),
  RD("sb_over_freq", SB, "spectra_dbm", "freq", "coord", { mode: "range", lo: "10", hi: "50 + wl/10" }, "inside", "max"),
  RD("sb_over_hz", SB, "spectra_dbm", "freq", "var:freq_Hz", { mode: "range", lo: "1G", hi: "20G" }, "inside", "mean"),
  RD("sb_cnt_undef", SB, "spectra_dbm", "wl", "var:wl_nm", { mode: "center", center: "sb_up_nm", halfwidth: "0.01" }, "outside", "count"),
  FM("sb_snr", SB, "sb_low_dbm - pump_dbm"),
  FM("sb_ghz", SB, '"freq_Hz"/1G'),
  FM("sb_mix", SB, "freq_Hz*1e-9 + freq"),
  FM("sb_lin", SB, "db2lin(sb_pump) - db2lin(sb_floor)"),
  FM("sb_rel", SB, "sb_pump - vna_power_actual"),

  RD("pc_pk", PC, "sa_trace", "sa_point", "var:sa_freq", { mode: "center", center: "frequency", halfwidth: "2M" }, "inside", "max"),
  RD("pc_fl", PC, "sa_trace", "sa_point", "var:sa_freq", { mode: "center", center: "frequency", halfwidth: "frequency*1e-3",
    halfwidth2: "frequency*0.02" }, "outside_within", "mean"),
  RD("pc_cnt", PC, "sa_trace", "sa_point", "var:sa_freq", { mode: "range", lo: "frequency*0.99", hi: "frequency*1.01" }, "inside", "count"),
  RD("pc_sw", PC, "sa_peak", "sweep", "index", { mode: "range", lo: "0", hi: "1" }, "inside", "mean"),
  RD("pc_fax", PC, "sa_peak_mean", "frequency", "coord", { mode: "center", center: "40G", halfwidth: "5G" }, "inside", "argmax_x"),
  RD("pc_vp", PC, "sa_trace", "sa_point", "var:sa_freq", { mode: "center", center: "frequency + vna_power*1M",
    halfwidth: "abs(vna_power)*100k" }, "inside", "max"),
  FM("pc_gain", PC, "sa_peak - vna_power"),
  FM("pc_g2", PC, "gain - (sa_peak_mean - vna_power)"),
  FM("pc_se", PC, "sa_peak_std/sqrt(3)"),
  FM("pc_lin", PC, "db2lin(sa_peak)"),
  FM("pc_snr", PC, "pc_pk - pc_fl"),
  FM("pc_idx", PC, "sweep*10 + sa_peak*0"),
];
const EXPECT_FAIL = new Set(["bad_dim", "bad_name", "bad_empty", "bad_over", "bad_syntax", "bad_f", "dep_bad"]);
const realFiles = [DA, SB, PC].filter((f) => haveData(f));
for (const f of [DA, SB, PC]) if (!haveData(f)) skip(`part 2 ${f}`, "tests/data file missing");
if (realFiles.length) {
  const defs = REAL_DEFS.filter((d) => realFiles.includes(d.file));
  const SPEC = { [DA]: { v: "laswrPowers", lineDim: "stimulusFrequency", xsrc: "coord", slices: { stimulusAmp: 0 } },
    [SB]: { v: "pump_dbm", lineDim: "freq", xsrc: "index" }, [PC]: { v: "gain", lineDim: "frequency", xsrc: "coord", slices: { vna_power: 0 } } };
  const proj = reportProject(realFiles.map((file) => ({ file, ...SPEC[file] })), defs);
  const script = P.buildReportScript(proj, { generatedAt: "2026-10-02T00:00:00.000Z" });
  const sp2 = path.join(TMP, "real.py"), dj = path.join(TMP, "real.json");
  fs.writeFileSync(sp2, script, "utf8");
  const r = runPy([sp2, "--data-dir", DATA_DIR, "--out", path.join(TMP, "real.pdf"), "--dump-derived", dj]);
  fs.writeFileSync(path.join(TMP, "real.out.txt"), r.out);
  if (check("part 2: script ran (exit 0)", r.status === 0, r.out.slice(-2000))) {
    const dump = JSON.parse(fs.readFileSync(dj, "utf8"));
    let nWin = 0, nForm = 0;
    for (const file of realFiles) {
      const fdefs = defs.filter((d) => d.file === file);
      const ds = await loadDataset(dataFile(file));
      // as the app loads them from a project (sanitizeDef migrates legacy windows)
      const st = D.registerDerived(ds, fdefs.map((d) => D.sanitizeDef(d)).filter(Boolean));
      for (const d of fdefs) {
        const s = st.get(d.name), pv = (dump[file] || {})[d.name], tag = `part 2 ${file} ${d.name}`;
        if (EXPECT_FAIL.has(d.name)) {
          check(`${tag}: fails in derive.js`, !s || !s.ok, s);
          check(`${tag}: fails in the script`, !pv, pv && pv.dims);
          continue;
        }
        if (!check(`${tag}: ok in derive.js`, s && s.ok, s && s.error)) { if (pv) findings.push({ part: "part 2", cat: "accept", text: d.name, detail: `js ${s && s.error} | script computed` }); continue; }
        if (!check(`${tag}: computed by the script`, !!pv, (r.out.match(new RegExp(`derived '${d.name}' .*`)) || [""])[0])) {
          findings.push({ part: "part 2", cat: "accept", text: d.name, detail: `js ok | script: ${(r.out.match(new RegExp(`derived '${d.name}' .*`)) || [""])[0]}` });
          continue;
        }
        const v = ds.vars[d.name];
        if (d.kind === "formula") nForm++; else if (d.window && d.window.mode !== "none") nWin++;
        const dimsOk = check(`${tag}: dims`, JSON.stringify(v.dims) === JSON.stringify(pv.dims) && JSON.stringify(v.shape) === JSON.stringify(pv.shape),
          [v.dims, pv.dims]);
        const unitsOk = check(`${tag}: units`, String(v.attrs.units) === pv.units, [v.attrs.units, pv.units]);
        const diff = dimsOk ? firstDiff(Array.from(v.data), pv.data.map((x) => (x === null ? NaN : x)), false, 1e-9) : "dims";
        const valsOk = check(`${tag}: values (rel 1e-9, NaN <-> NaN)`, !diff, diff);
        if (!dimsOk || !unitsOk || !valsOk) findings.push({ part: "part 2", cat: "value", text: d.name, detail: diff || `units ${v.attrs.units} vs ${pv.units}` });
        const nNaN = Array.from(v.data).filter((x) => x !== x).length;
        if (["undef", "sb_low_pk"].includes(d.name)) check(`${tag}: has undefined (NaN) elements`, nNaN > 0 && nNaN < v.data.length, nNaN);
      }
    }
    console.log(`part 2: ${nWin} expression-window defs and ${nForm} formulas compared on ${realFiles.join(", ")}`);
    check("part 2: >= 20 defs compared", nWin + nForm >= 20, nWin + nForm);
  }
}

// ---- part 2b: only ONE plotted def; its dependencies are reachable only through
// expressions (window fields, quoted names), so neededDerived must follow them
if (haveData(DA)) {
  const D2 = (name, win, region, stat) => RD(name, DA, "spectrums", "TraceIndex", "var:frequencies", win, region, stat);
  const defs = [
    FM("hw d", DA, "3*ResolutionBWs"),
    D2("pk2", { mode: "center", center: "stimulusFrequency", halfwidth: '"hw d"' }, "inside", "max"),
    D2("ax2", { mode: "range", lo: "0.5*stimulusFrequency", hi: "1.5*stimulusFrequency" }, "inside", "argmax_x"),
    D2("pkax2", { mode: "center", center: "ax2", halfwidth: 'max("hw d", 1k)', lo: "unneeded" }, "inside", "max"),
    D2("fl2", { mode: "center", center: "stimulusFrequency", halfwidth: '"hw d"', halfwidth2: "0.2*stimulusFrequency" }, "outside_within", "mean"),
    FM("snr q", DA, "pk2 - fl2"),
    FM("top", DA, '"snr q" + 0*pkax2'),
    FM("unneeded", DA, "1/0"),
  ];
  const tabs = [{ name: "top", plotcfg: { ...X.DEFAULT_PLOTCFG }, markers: [], cur: 0,
    traces: [X.makeTrace(DA, "top", "stimulusFrequency", "coord", "", { stimulusAmp: 0, trace: 0 })] }];
  const proj = JSON.parse(JSON.stringify(PJ.buildProject({ tabs, active: 0, fileOrder: [DA], wantedFiles: [], derived: defs })));
  const exported = P.neededDerived(proj).map((d) => d.name);
  check("part 2b: neededDerived follows expression references", JSON.stringify(exported.slice().sort())
    === JSON.stringify(["ax2", "fl2", "hw d", "pk2", "pkax2", "snr q", "top"]), exported);
  const sp3 = path.join(TMP, "chain.py"), dj = path.join(TMP, "chain.json");
  fs.writeFileSync(sp3, P.buildReportScript(proj, { generatedAt: "2026-10-02T00:00:00.000Z" }), "utf8");
  const r = runPy([sp3, "--data-dir", DATA_DIR, "--out", path.join(TMP, "chain.pdf"), "--dump-derived", dj]);
  if (check("part 2b: script ran (exit 0, page drawn)", r.status === 0 && !/skipped/.test(r.out), r.out.slice(-1500))) {
    const dump = JSON.parse(fs.readFileSync(dj, "utf8"))[DA] || {};
    const ds = await loadDataset(dataFile(DA));
    const st = D.registerDerived(ds, defs);
    for (const n of exported) {
      const pv = dump[n], v = ds.vars[n];
      if (!check(`part 2b: ${n} computed by both`, !!pv && st.get(n) && st.get(n).ok, [!!pv, st.get(n)])) continue;
      const diff = firstDiff(Array.from(v.data), pv.data.map((x) => (x === null ? NaN : x)), false, 1e-9);
      check(`part 2b: ${n} dims/units/values`, !diff && JSON.stringify(v.dims) === JSON.stringify(pv.dims)
        && String(v.attrs.units) === pv.units, diff || [v.dims, pv.dims, v.attrs.units, pv.units]);
    }
  }
}

// ============================================================ summary
if (findings.length) {
  console.log(`\n${findings.length} mismatch categor${findings.length === 1 ? "y" : "ies"}:`);
  for (const f of findings) console.log(`  ${f.part} [${f.cat}] ${JSON.stringify(f.text).slice(0, 120)} -> ${f.detail}`);
}
console.log(`(${((Date.now() - T0) / 1000).toFixed(1)} s; temp folder ${KEEP ? TMP : "removed"})`);
if (!KEEP) { try { fs.rmSync(TMP, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); } catch (e) { console.log(`could not remove ${TMP}: ${e.message}`); } }
summary("expr_parity");
